Admin dashboard
turingschool/present pull request #241
Opened 2023-08-11 22:51 UTC by AlejandroLopez1992

____ Wrote Tests ____ Implemented ____ Reviewed

## Necessary checkmarks:

- [X] All Tests are Passing in all environments

- [X] The code will run locally

## Type of change

- [X] New feature
- [ ] Bug Fix
- [ ] Refactor

## Description of Change:

    description: Add button to nav bar appearing to admin users to redirect to admin dashboard show page
    created admin dashboard page and added header

## Requested feedback:

    I'd like feedback on the /app/views/layouts/application.html.erb lines 22-24, if it is acceptable to use that amount of logic 
    in the application.html file and if not how can we abstract it. - Alejandro
    I'd like feedback on the /app/views/layouts/application.html.erb lines 22-24, is it acceptable that we decided not to include 
    the admin button onto the admin dashboard page. - Alec

## Check the correct boxes

- [X] This broke nothing
- [ ] This broke some stuff
- [ ] This broke everything

## Testing Changes

- [X] No Tests have been changed
- [ ] Some Tests have been changed
- [ ] All of the Tests have been changed(Please describe what in the world happened)

## Checklist:

- [X] My code has no unused/commented out code
- [X] My code has no binding.pry's
- [X] I have reviewed my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have fully tested my code

(For Fun!)Please Include a link to a gif of your feelings about this branch

Link: https://tenor.com/view/elmo-dancing-happy-excited-mouth-open-gif-16032246

2023-08-11 23:04 UTC, BrianZanti requested changes
This is looking really good! I did have a couple of comments I'd like you all to resolve. Additionally, I'd like you all to add a test to the `security_spec` that if a non-admin tries to manually visit `/admin` in their browser then they receive the message that they are not allowed to view the page. You can find some similar expectations for visiting the slack_presence_checks page in that file.

2023-08-11 23:04 UTC, BrianZanti commented on app/views/layouts/application.html.erb
> +            <% if current_user.admin? && request.path != '/admin' %>
I don't think you need the second condition here to check the request path. If the user is already on the `/admin` page it's fine to still display the admin link. It would just take them back to the admin dashboard

2023-08-11 23:04 UTC, BrianZanti commented on app/views/layouts/application.html.erb
> +              <%= content_tag(:li, button_to('Admin', '/admin'), method: :get, class: 's-nav-menu-item', style: 'margin-right: 2px;') %>
For consistency, let's skip using the view helper `content_tag` and stick with a raw html <li> element. Also, we want to avoid inline styling. Instead, if you need to style this link give it an id and then target it with CSS in the `application.css` file.

2023-08-11 23:04 UTC, BrianZanti commented on config/routes.rb
> +    get '/', to: 'dashboard#show'
👍

2023-08-11 23:04 UTC, BrianZanti commented on config/routes.rb
> +    get '/', to: 'dashboard#show'
👍

2023-08-11 23:04 UTC, BrianZanti commented on app/views/layouts/application.html.erb
> +              <%= content_tag(:li, button_to('Admin', '/admin'), method: :get, class: 's-nav-menu-item', style: 'margin-right: 2px;') %>
For consistency, let's skip using the view helper `content_tag` and stick with a raw html `<li>` element like the links above. Also, we want to avoid inline styling. Instead, if you need to style this link give it an id and then target it with CSS in the `application.css` file.

2023-08-11 23:04 UTC, BrianZanti commented on spec/features/admin/dashboard_spec.rb
> +      expect(page).to_not have_button("Admin")
We don't need this expectation per my comment above. I'd prefer to still display the link to the admin dashboard even if they're already there.

2023-08-11 23:04 UTC, BrianZanti commented on spec/features/nav_spec.rb
>  end
👍

2023-08-14 16:46 UTC, AlejandroLopez1992 commented on app/views/layouts/application.html.erb
> +            <% if current_user.admin? && request.path != '/admin' %>
Sounds good, updated and testing changes to accommodate it within dashboard_spec

2023-08-14 16:52 UTC, AlejandroLopez1992 commented on app/views/layouts/application.html.erb
> +              <%= content_tag(:li, button_to('Admin', '/admin'), method: :get, class: 's-nav-menu-item', style: 'margin-right: 2px;') %>
Thank you

2023-08-18 15:11 UTC, BrianZanti approved these changes

2023-08-18 15:11 UTC, merged